#pragma once

typedef enum tester_event_t
{
    TESTER_EVENT_INTERFACE_DISCONNECTED,
    TESTER_EVENT_INTERFACE_SETTLED,
    TESTER_EVENT_INTERVAL_TIMER_ELAPSED,
    TESTER_EVENT_TEST_PASSED,
    TESTER_EVENT_TEST_FAILED,
    TESTER_EVENT_TEST_TIMED_OUT,
    TESTER_EVENT_RECOVERY_TASK_ENDED,
    TESTER_EVENT_RECOVERY_TASK_TIMED_OUT,
    TESTER_EVENT_COUNT__, /* Must be last. */
} tester_event_t;

